import {
  User,
  UserRole,
  Plant,
  PlantCategory,
  PlantVariant,
  CarePackage,
  Material,
  PlantInstance,
  Order,
  OrderStatus,
  CareServiceRequest,
  CareServiceStatus,
  ServicePackageType,
  CaretakerInfo,
  CaretakerStatus,
} from '@/types';

// Test Accounts by Role
export const MOCK_USERS: Record<UserRole, User> = {
  [UserRole.GUEST]: {
    id: 'guest-001',
    email: 'guest@plantdecor.com',
    password: 'guest123',
    name: 'Guest User',
    role: UserRole.GUEST,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    isActive: true,
  },
  [UserRole.CUSTOMER]: {
    id: 'customer-001',
    email: 'customer@plantdecor.com',
    password: 'customer123',
    name: 'Nguyen Van A',
    role: UserRole.CUSTOMER,
    phone: '0912345678',
    address: '123 Nguyen Hue, Ho Chi Minh City',
    avatar: 'https://ui-avatars.com/api/?name=Nguyen+Van+A',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-20'),
    isActive: true,
  },
  [UserRole.ADMIN]: {
    id: 'admin-001',
    email: 'admin@plantdecor.com',
    password: 'admin123',
    name: 'Admin Manager',
    role: UserRole.ADMIN,
    phone: '0923456789',
    avatar: 'https://ui-avatars.com/api/?name=Admin+Manager',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2025-01-25'),
    isActive: true,
  },
  [UserRole.SUPPORT_STAFF]: {
    id: 'support-001',
    email: 'support@plantdecor.com',
    password: 'support123',
    name: 'Tran Thi B',
    role: UserRole.SUPPORT_STAFF,
    phone: '0934567890',
    avatar: 'https://ui-avatars.com/api/?name=Tran+Thi+B',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2025-01-20'),
    isActive: true,
  },
  [UserRole.SHIPPER]: {
    id: 'shipper-001',
    email: 'shipper@plantdecor.com',
    password: 'shipper123',
    name: 'Le Van C',
    role: UserRole.SHIPPER,
    phone: '0945678901',
    avatar: 'https://ui-avatars.com/api/?name=Le+Van+C',
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2025-01-22'),
    isActive: true,
  },
  [UserRole.CARETAKER]: {
    id: 'caretaker-001',
    email: 'caretaker@plantdecor.com',
    password: 'caretaker123',
    name: 'Pham Thi D',
    role: UserRole.CARETAKER,
    phone: '0956789012',
    avatar: 'https://ui-avatars.com/api/?name=Pham+Thi+D',
    createdAt: new Date('2024-12-18'),
    updatedAt: new Date('2025-01-21'),
    isActive: true,
  },
};

// Plant Categories
export const PLANT_CATEGORIES: PlantCategory[] = [
  { id: 'cat-1', name: 'Indoor Plants', description: 'Plants suitable for indoor environments' },
  { id: 'cat-2', name: 'Outdoor Plants', description: 'Plants for gardens and outdoor spaces' },
  { id: 'cat-3', name: 'Succulents', description: 'Low-maintenance succulent plants' },
  { id: 'cat-4', name: 'Flowering Plants', description: 'Beautiful flowering varieties' },
  { id: 'cat-5', name: 'Herbs', description: 'Edible and medicinal herbs' },
];

// Mock Plants
export const MOCK_PLANTS: Plant[] = [
  {
    id: 'plant-001',
    name: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    category: PLANT_CATEGORIES[0],
    description: 'Popular indoor plant with large, distinctive leaves. Perfect for modern interiors.',
    price: 299000,
    image: 'https://picsum.photos/seed/monstera/400/400',
    stock: 15,
    rating: 4.8,
    reviewCount: 342,
    difficulty: 'easy',
    wateringFrequency: 'Every 5-7 days',
    sunlightRequirement: 'Bright, indirect light',
    humidity: '50-60%',
    temperature: '18-27°C',
    careInstructions: {
      watering: 'Water when top inch of soil is dry',
      sunlight: 'Bright, indirect light preferred',
      humidity: 'Prefers moderate to high humidity',
      temperature: '18-27°C ideal',
      fertilizing: 'Monthly during growing season',
      pruning: 'Remove dead leaves occasionally',
      commonPests: ['Spider mites', 'Mealybugs'],
      propagation: 'Stem cuttings in water or soil',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'plant-002',
    name: 'Pothos (Devil\'s Ivy)',
    scientificName: 'Epipremnum aureum',
    category: PLANT_CATEGORIES[0],
    description: 'Trailing vine plant. Very forgiving and great for beginners.',
    price: 149000,
    image: 'https://picsum.photos/seed/pothos/400/400',
    stock: 32,
    rating: 4.9,
    reviewCount: 561,
    difficulty: 'easy',
    wateringFrequency: 'Every 1-2 weeks',
    sunlightRequirement: 'Low to medium indirect light',
    humidity: '40-50%',
    temperature: '15-27°C',
    careInstructions: {
      watering: 'Allow soil to dry between waterings',
      sunlight: 'Tolerates low light well',
      humidity: 'Adapts to average humidity',
      temperature: '15-27°C',
      fertilizing: 'Every 1-2 months during growth',
      pruning: 'Trim to control growth',
      commonPests: ['Mealybugs'],
      propagation: 'Very easy from stem cuttings',
    },
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'plant-003',
    name: 'Snake Plant',
    scientificName: 'Sansevieria trifasciata',
    category: PLANT_CATEGORIES[3],
    description: 'Extremely hardy succulent. Air-purifying and perfect for low-light areas.',
    price: 199000,
    image: 'https://picsum.photos/seed/snakeplant/400/400',
    stock: 25,
    rating: 4.7,
    reviewCount: 428,
    difficulty: 'easy',
    wateringFrequency: 'Every 2-3 weeks',
    sunlightRequirement: 'Any light, thrives in low light',
    humidity: '30-40%',
    temperature: '13-29°C',
    careInstructions: {
      watering: 'Water sparingly, let soil dry completely',
      sunlight: 'Tolerates any light condition',
      humidity: 'Low humidity tolerance',
      temperature: '13-29°C',
      fertilizing: 'Spring only',
      pruning: 'Minimal pruning needed',
      commonPests: ['Root rot if overwatered'],
      propagation: 'Leaf cuttings or division',
    },
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'plant-004',
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum wallisii',
    category: PLANT_CATEGORIES[0],
    description: 'Elegant plant with white flowers. Signals when thirsty by drooping.',
    price: 249000,
    image: 'https://picsum.photos/seed/peacelily/400/400',
    stock: 18,
    rating: 4.6,
    reviewCount: 312,
    difficulty: 'easy',
    wateringFrequency: 'Every 3-4 days',
    sunlightRequirement: 'Low to medium indirect light',
    humidity: '50-60%',
    temperature: '16-27°C',
    careInstructions: {
      watering: 'Keep soil moist but not soggy',
      sunlight: 'Prefers low to medium light',
      humidity: 'Likes humidity, mist leaves',
      temperature: '16-27°C',
      fertilizing: 'Monthly during growth season',
      pruning: 'Remove dead leaves and flowers',
      commonPests: ['Spider mites', 'Mealybugs'],
      propagation: 'Division of root ball',
    },
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'plant-005',
    name: 'Rubber Plant',
    scientificName: 'Ficus elastica',
    category: PLANT_CATEGORIES[0],
    description: 'Bold, dramatic plant with large shiny leaves. Makes a statement in any room.',
    price: 399000,
    image: 'https://picsum.photos/seed/rubberplant/400/400',
    stock: 10,
    rating: 4.5,
    reviewCount: 287,
    difficulty: 'medium',
    wateringFrequency: 'Every 1-2 weeks',
    sunlightRequirement: 'Bright, indirect light',
    humidity: '50%',
    temperature: '15-27°C',
    careInstructions: {
      watering: 'Water when top 2 inches dry',
      sunlight: 'Bright indirect light needed',
      humidity: 'Moderate humidity preferred',
      temperature: '15-27°C',
      fertilizing: 'Every 2-4 weeks in growing season',
      pruning: 'Prune to maintain shape',
      commonPests: ['Scale insects', 'Mealybugs'],
      propagation: 'Air layering or cuttings',
    },
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'plant-006',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis',
    category: PLANT_CATEGORIES[2],
    description: 'Medicinal succulent with healing gel. Requires minimal care.',
    price: 129000,
    image: 'https://picsum.photos/seed/aloevera/400/400',
    stock: 40,
    rating: 4.8,
    reviewCount: 523,
    difficulty: 'easy',
    wateringFrequency: 'Every 2-3 weeks',
    sunlightRequirement: 'Bright light, tolerates partial shade',
    humidity: '20-30%',
    temperature: '13-27°C',
    careInstructions: {
      watering: 'Water sparingly, very drought tolerant',
      sunlight: 'Bright light preferred',
      humidity: 'Very low humidity tolerance',
      temperature: '13-27°C',
      fertilizing: 'Rarely needed',
      pruning: 'Remove dead leaves',
      commonPests: ['Root rot if overwatered'],
      propagation: 'Offsets or leaf cuttings',
    },
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'plant-007',
    name: 'Japanese Bonsai Tree',
    scientificName: 'Ficus retusa',
    category: PLANT_CATEGORIES[1],
    description: 'Traditional Japanese bonsai. Each tree has a unique shape and character. Choose the specific tree you love.',
    price: 899000,
    image: 'https://picsum.photos/seed/bonsai/400/400',
    stock: 8,
    rating: 4.9,
    reviewCount: 127,
    difficulty: 'medium',
    wateringFrequency: 'Every 1-2 days',
    sunlightRequirement: 'Bright, indirect light (6+ hours)',
    humidity: '60-70%',
    temperature: '15-25°C',
    variants: [
      {
        id: 'bonsai-tree-001',
        plantId: 'plant-007',
        image: 'https://picsum.photos/seed/bonsai1/600/600',
        price: 899000,
        stock: 1,
        isSold: false,
      },
      {
        id: 'bonsai-tree-002',
        plantId: 'plant-007',
        image: 'https://picsum.photos/seed/bonsai2/600/600',
        price: 1299000,
        stock: 1,
        isSold: false,
      },
      {
        id: 'bonsai-tree-003',
        plantId: 'plant-007',
        image: 'https://picsum.photos/seed/bonsai3/600/600',
        price: 799000,
        stock: 1,
        isSold: false,
      },
      {
        id: 'bonsai-tree-004',
        plantId: 'plant-007',
        image: 'https://picsum.photos/seed/bonsai4/600/600',
        price: 699000,
        stock: 1,
        isSold: false,
      },
      {
        id: 'bonsai-tree-005',
        plantId: 'plant-007',
        image: 'https://picsum.photos/seed/bonsai5/600/600',
        price: 1499000,
        stock: 1,
        isSold: false,
      },
      {
        id: 'bonsai-tree-006',
        plantId: 'plant-007',
        image: 'https://picsum.photos/seed/bonsai6/600/600',
        price: 950000,
        stock: 1,
        isSold: false,
      },
    ],
    careInstructions: {
      watering: 'Keep soil consistently moist but not waterlogged. Water daily or every other day.',
      sunlight: 'Needs 6+ hours of bright, indirect light daily',
      humidity: 'Mist daily to maintain humidity around 60-70%',
      temperature: '15-25°C. Avoid sudden temperature changes.',
      fertilizing: 'Every 2-3 weeks during growing season (spring-summer)',
      pruning: 'Regular pruning and wiring to maintain shape. Pinch new growth.',
      commonPests: ['Spider mites', 'Scale insects', 'Mealybugs'],
      propagation: 'Cuttings or air layering',
    },
    createdAt: new Date('2025-01-07'),
    updatedAt: new Date('2025-01-20'),
  },
];

// Care Packages - 3 gói dịch vụ theo quy trình nghiệp vụ
export const MOCK_CARE_PACKAGES: CarePackage[] = [
  {
    id: 'pkg-doctor',
    name: 'Gói Bác sĩ Cây xanh',
    type: ServicePackageType.PLANT_DOCTOR,
    description: 'Chẩn đoán và chữa bệnh cho cây. Phù hợp khi cây có dấu hiệu bệnh, sâu bệnh hoặc phát triển không tốt.',
    price: 500000,
    duration: 2, // hours
    services: [
      'Khám tổng quát sức khỏe cây',
      'Chẩn đoán bệnh và sâu hại',
      'Điều trị bệnh tại chỗ',
      'Kê đơn thuốc/phân bón',
      'Hướng dẫn chăm sóc hậu điều trị',
      'Báo cáo chi tiết tình trạng cây',
    ],
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'pkg-spa',
    name: 'Gói Spa Cây cảnh',
    type: ServicePackageType.PLANT_SPA,
    description: 'Vệ sinh, cắt tỉa và bón phân cho cây. Giúp cây luôn xanh tốt, đẹp mắt.',
    price: 350000,
    duration: 1.5, // hours
    services: [
      'Vệ sinh lá và thân cây',
      'Cắt tỉa cành, lá vàng/khô',
      'Tạo dáng cây (nếu cần)',
      'Bón phân chuyên dụng',
      'Thay đất mặt',
      'Kiểm tra sức khỏe tổng quát',
    ],
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'pkg-consult',
    name: 'Gói Tư vấn & Setup',
    type: ServicePackageType.CONSULTATION_SETUP,
    description: 'Cải tạo môi trường sống cho cây. Tư vấn vị trí đặt cây, ánh sáng, độ ẩm phù hợp.',
    price: 800000,
    duration: 3, // hours
    services: [
      'Khảo sát không gian',
      'Đánh giá điều kiện ánh sáng, độ ẩm',
      'Tư vấn loại cây phù hợp',
      'Thiết kế layout đặt cây',
      'Hướng dẫn lịch chăm sóc',
      'Báo cáo và bản vẽ setup',
      'Hỗ trợ mua cây (nếu cần)',
    ],
    createdAt: new Date('2025-01-01'),
  },
];

// Materials (Pots, soil, fertilizer, etc.)
export const MOCK_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    name: 'Ceramic Pot 6"',
    type: 'pot',
    description: 'Beautiful ceramic pot with drainage hole, 6 inches diameter',
    price: 79000,
    stock: 50,
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'mat-2',
    name: 'Potting Soil Mix',
    type: 'soil',
    description: 'Premium potting soil for indoor plants, 5L bag',
    price: 45000,
    stock: 100,
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'mat-3',
    name: 'Liquid Fertilizer',
    type: 'fertilizer',
    description: 'All-purpose liquid fertilizer, 500ml bottle',
    price: 35000,
    stock: 75,
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'mat-4',
    name: 'Plant Mister',
    type: 'tool',
    description: 'Spray bottle for misting leaves, 500ml capacity',
    price: 25000,
    stock: 40,
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'mat-5',
    name: 'Pruning Shears',
    type: 'tool',
    description: 'Stainless steel pruning shears for plant maintenance',
    price: 89000,
    stock: 30,
    createdAt: new Date('2025-01-01'),
  },
];

// Mock Customer's Plant Instances
export const MOCK_PLANT_INSTANCES: PlantInstance[] = [
  {
    id: 'instance-1',
    customerId: 'customer-001',
    plantId: 'plant-001',
    plantName: 'Monstera Deliciosa',
    plantImage: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=300&h=300&fit=crop',
    location: 'Living Room',
    purchaseDate: new Date('2024-12-15'),
    quantity: 1,
    lastCaredDate: new Date('2025-01-29'),
    healthStatus: 'excellent',
    careHistory: [
      {
        id: 'log-1',
        date: new Date('2025-01-29'),
        action: 'Watered',
        notes: 'Plant looks healthy, new leaf emerging',
        recordedBy: 'Caretaker - Pham Thi D',
      },
      {
        id: 'log-2',
        date: new Date('2025-01-22'),
        action: 'Watered',
        notes: 'Leaves dusted, looks vibrant',
        recordedBy: 'Customer',
      },
    ],
    notes: 'Placed near window, getting good indirect light',
  },
  {
    id: 'instance-2',
    customerId: 'customer-001',
    plantId: 'plant-006',
    plantName: 'Aloe Vera',
    plantImage: 'https://images.unsplash.com/photo-1611904707267-471b28bb98f0?w=300&h=300&fit=crop',
    location: 'Bedroom',
    purchaseDate: new Date('2025-01-10'),
    quantity: 2,
    lastCaredDate: new Date('2025-01-28'),
    healthStatus: 'good',
    careHistory: [
      {
        id: 'log-3',
        date: new Date('2025-01-28'),
        action: 'Checked',
        notes: 'No watering needed, soil still moist',
        recordedBy: 'Customer',
      },
    ],
    notes: 'On sunny windowsill, very low maintenance',
  },
];

// Mock Orders
export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-001',
    customerId: 'customer-001',
    items: [
      {
        id: 'item-1',
        plantId: 'plant-001',
        plantName: 'Monstera Deliciosa',
        quantity: 1,
        price: 299000,
        subtotal: 299000,
      },
    ],
    totalPrice: 299000,
    status: OrderStatus.DELIVERED,
    shipperId: 'shipper-001',
    shippingAddress: '123 Nguyen Hue, Ho Chi Minh City',
    paymentMethod: 'Credit Card',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-25'),
    deliveryDate: new Date('2024-12-25'),
    trackingNumber: 'PD001-DEC-2024',
  },
  {
    id: 'order-002',
    customerId: 'customer-001',
    items: [
      {
        id: 'item-2',
        plantId: 'plant-006',
        plantName: 'Aloe Vera',
        quantity: 2,
        price: 129000,
        subtotal: 258000,
      },
      {
        id: 'item-3',
        plantId: 'mat-2',
        plantName: 'Potting Soil Mix',
        quantity: 1,
        price: 45000,
        subtotal: 45000,
      },
    ],
    totalPrice: 303000,
    status: OrderStatus.SHIPPED,
    shipperId: 'shipper-001',
    shippingAddress: '123 Nguyen Hue, Ho Chi Minh City',
    paymentMethod: 'Bank Transfer',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-10'),
    trackingNumber: 'PD002-JAN-2025',
  },
  {
    id: 'order-003',
    customerId: 'customer-001',
    items: [
      {
        id: 'item-4',
        plantId: 'plant-002',
        plantName: "Pothos (Devil's Ivy)",
        quantity: 1,
        price: 149000,
        subtotal: 149000,
      },
    ],
    totalPrice: 149000,
    status: OrderStatus.PENDING,
    shippingAddress: '123 Nguyen Hue, Ho Chi Minh City',
    paymentMethod: 'Credit Card',
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
];

// Mock Care Service Requests - theo quy trình nghiệp vụ mới
export const MOCK_CARE_SERVICE_REQUESTS: CareServiceRequest[] = [
  {
    id: 'service-001',
    customerId: 'customer-001',
    customerName: 'Nguyen Van A',
    customerPhone: '0912345678',
    customerEmail: 'customer@plantdecor.com',
    customerAddress: '123 Nguyen Hue, Ho Chi Minh City',
    workAddress: undefined,
    packageId: 'pkg-spa',
    packageName: 'Gói Spa Cây cảnh',
    packageType: ServicePackageType.PLANT_SPA,
    plantIds: ['plant-001'],
    plantNames: ['Monstera Deliciosa'],
    status: CareServiceStatus.IN_PROGRESS,
    scheduledDate: new Date('2026-02-05'),
    estimatedCompletionDate: new Date('2026-02-05'),
    mainCaretakerId: 'caretaker-001',
    mainCaretakerName: 'Pham Thi D',
    currentCaretakerId: 'caretaker-001',
    currentCaretakerName: 'Pham Thi D',
    confirmedBy: 'support-001',
    confirmedAt: new Date('2026-02-01'),
    checkInTime: new Date('2026-02-05T09:00:00'),
    progressLogs: [
      {
        id: 'log-001',
        serviceRequestId: 'service-001',
        caretakerId: 'caretaker-001',
        caretakerName: 'Pham Thi D',
        action: 'Check-in',
        description: 'Đã đến nhà khách hàng, bắt đầu công việc',
        timestamp: new Date('2026-02-05T09:00:00'),
      },
      {
        id: 'log-002',
        serviceRequestId: 'service-001',
        caretakerId: 'caretaker-001',
        caretakerName: 'Pham Thi D',
        action: 'Vệ sinh lá',
        description: 'Đã vệ sinh sạch các lá, loại bỏ bụi bẩn',
        photos: ['https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=300'],
        timestamp: new Date('2026-02-05T09:30:00'),
      },
    ],
    addOnServices: [],
    basePrice: 350000,
    addOnTotal: 0,
    totalPrice: 350000,
    customerNotes: 'Cây ở phòng khách, cần làm sạch và cắt tỉa',
    internalNotes: 'Khách hàng VIP, cần chăm sóc cẩn thận',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'service-002',
    customerId: 'customer-001',
    customerName: 'Nguyen Van A',
    customerPhone: '0912345678',
    customerEmail: 'customer@plantdecor.com',
    customerAddress: '123 Nguyen Hue, Ho Chi Minh City',
    packageId: 'pkg-doctor',
    packageName: 'Gói Bác sĩ Cây xanh',
    packageType: ServicePackageType.PLANT_DOCTOR,
    plantIds: ['plant-006'],
    plantNames: ['Aloe Vera'],
    status: CareServiceStatus.PENDING,
    scheduledDate: new Date('2026-02-10'),
    progressLogs: [],
    addOnServices: [],
    basePrice: 500000,
    addOnTotal: 0,
    totalPrice: 500000,
    customerNotes: 'Cây có dấu hiệu vàng lá, cần kiểm tra',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'service-003',
    customerId: 'customer-001',
    customerName: 'Nguyen Van A',
    customerPhone: '0912345678',
    customerEmail: 'customer@plantdecor.com',
    customerAddress: '123 Nguyen Hue, Ho Chi Minh City',
    packageId: 'pkg-consult',
    packageName: 'Gói Tư vấn & Setup',
    packageType: ServicePackageType.CONSULTATION_SETUP,
    plantIds: [],
    plantNames: [],
    status: CareServiceStatus.CONFIRMED,
    scheduledDate: new Date('2026-02-08'),
    mainCaretakerId: 'caretaker-001',
    mainCaretakerName: 'Pham Thi D',
    currentCaretakerId: 'caretaker-001',
    currentCaretakerName: 'Pham Thi D',
    confirmedBy: 'support-001',
    confirmedAt: new Date('2026-02-02'),
    progressLogs: [],
    addOnServices: [],
    basePrice: 800000,
    addOnTotal: 0,
    totalPrice: 800000,
    customerNotes: 'Muốn tư vấn setup góc cây cho phòng làm việc',
    createdAt: new Date('2026-02-02'),
    updatedAt: new Date('2026-02-02'),
  },
];

// Mock Caretaker Info với trạng thái
export const MOCK_CARETAKERS: CaretakerInfo[] = [
  {
    userId: 'caretaker-001',
    name: 'Pham Thi D',
    phone: '0956789012',
    skills: [ServicePackageType.PLANT_DOCTOR, ServicePackageType.PLANT_SPA, ServicePackageType.CONSULTATION_SETUP],
    status: CaretakerStatus.BUSY,
    currentTaskId: 'service-001',
  },
  {
    userId: 'caretaker-002',
    name: 'Tran Van E',
    phone: '0967890123',
    skills: [ServicePackageType.PLANT_SPA],
    status: CaretakerStatus.AVAILABLE,
  },
  {
    userId: 'caretaker-003',
    name: 'Nguyen Thi F',
    phone: '0978901234',
    skills: [ServicePackageType.PLANT_DOCTOR, ServicePackageType.PLANT_SPA],
    status: CaretakerStatus.ON_LEAVE,
  },
];

// Pagination helper
export function paginate<T>(items: T[], page: number, limit: number) {
  const start = (page - 1) * limit;
  const end = start + limit;
  return {
    data: items.slice(start, end),
    total: items.length,
    page,
    limit,
    totalPages: Math.ceil(items.length / limit),
  };
}
